# Generated by Django 3.0.8 on 2020-09-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('imgurl', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('imgurl', models.CharField(default='https://placehold.it/500x500', max_length=1000)),
                ('s_teacher', models.ManyToManyField(to='lessons.Teacher')),
            ],
        ),
    ]
