# Generated by Django 3.0.8 on 2020-09-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20200922_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='imgurl',
            field=models.ImageField(upload_to=''),
        ),
    ]
