# Generated by Django 3.0.8 on 2020-09-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20200924_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='imgurl',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
