# Generated by Django 3.0.8 on 2020-09-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20200925_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='imgurl',
        ),
        migrations.AddField(
            model_name='item',
            name='itemurl',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
