# Generated by Django 3.0.8 on 2020-09-27 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_itemtypes_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='item',
            name='itemsize',
            field=models.CharField(default='', max_length=100),
        ),
    ]
